import type { Metadata } from "next";
import "../../assets/sass/core.scss";
import HeaderComponent from "src/components/layout/header.component";
import { merriweather_Sans } from "../utils/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={merriweather_Sans.className}>
      <body>
        <HeaderComponent />
        {children}
      </body>
    </html>
  );
}
