name: Clean up Preview Deployment
on:
  push:
    branches:
      - 'main'

jobs:
  delete-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Neon Branch
        uses: neondatabase/delete-branch-action@v3.1.3
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch_id: br-floral-resonance-a2e2y31y
          api_key: ${{ secrets.NEON_API_KEY }}
