name: Clean up Preview Deployment
on:
  push:
    branches:
      - "main"

jobs:
  delete-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Neon Branch
        uses: neondatabase/delete-branch-action@v3.1.3
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch: ${{ secrets.BRANCH_ID }}
          api_key: ${{ secrets.NEON_API_KEY }}
