name: Clean up Preview Deployment
on:
  push:
    branches:
      - 'main'

jobs:
  delete-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Neon API api Key
        run: echo "NEON_API_KEY=${{ secrets.NEON_API_KEY }}" >> $GITHUB_ENV
      - name: Run clean up
        uses: neondatabase/delete-branch-action@v3.1.3
        env: 
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch: preview/pr-${{ github.event.number }}-${{ github.event.pull_request.head.ref }}
          api_key: $NEON_API_KEY
